#:schema https://raw.githubusercontent.com/cloudflare/workers-sdk/main/packages/wrangler/config-schema.json
name = "laundr"
compatibility_date = "2024-04-03"
compatibility_flags = ["nodejs_compat"]

[pages_build_config]
build_command = "pnpm run build"
destination_dir = "dist"
