# The name of your application.
name = "laundr"

# This property is required for Cloudflare Pages to correctly parse the config file.
pages_build_output_dir = "dist"

# The date of the Workers runtime version to use.
compatibility_date = "2026-01-01"

# Enable Node.js compatibility mode.
compatibility_flags = ["nodejs_compat"]
